services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_PROVIDER=${DB_PROVIDER}
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 1
      start_period: 30s  # Give more time for migration and seeding

  db:
    image: postgres:14-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:?}
      - POSTGRES_PASSWORD=${DB_PASSWORD:?}
      - POSTGRES_DB=${DB_NAME:?}
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:?} -d ${DB_NAME:?}"]
      interval: 10s
      timeout: 3s
      retries: 1
      start_period: 10s

volumes:
  postgres-data:
